/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#ab3500',
        'primary-container': '#ff6b35',
        'on-primary': '#ffffff',
        'on-primary-container': '#5f1900',
        'surface-tint': '#ab3500',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59d',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#832600',
        'inverse-primary': '#ffb59d',

        secondary: '#5b5b7e',
        'on-secondary': '#ffffff',
        'secondary-container': '#d8d6ff',
        'on-secondary-container': '#5c5c7f',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c4c3eb',
        'on-secondary-fixed': '#181837',
        'on-secondary-fixed-variant': '#444465',

        tertiary: '#00677e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00a7cb',
        'on-tertiary-container': '#003744',
        'tertiary-fixed': '#b5ebff',
        'tertiary-fixed-dim': '#59d5fb',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary-fixed-variant': '#004e60',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        background: '#fcf8ff',
        'on-background': '#181837',
        surface: '#fcf8ff',
        'surface-bright': '#fcf8ff',
        'surface-dim': '#d8d6ff',
        'surface-variant': '#e2dfff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#efecff',
        'surface-container-high': '#e8e5ff',
        'surface-container-highest': '#e2dfff',

        'on-surface': '#181837',
        'on-surface-variant': '#594139',
        'inverse-surface': '#2d2d4d',
        'inverse-on-surface': '#f2efff',

        outline: '#8d7168',
        'outline-variant': '#e1bfb5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'display-lg': ['Montserrat', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['Montserrat', 'system-ui', 'sans-serif'],
        'headline-md': ['Montserrat', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'code-ticket': ['JetBrains Mono', 'monospace'],
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', fontWeight: '700' }],
        'code-ticket': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      keyframes: {
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        ticketFly: {
          '0%': { opacity: '1', transform: 'translateY(100vh) rotate(0deg)' },
          '100%': { opacity: '0', transform: 'translateY(-100vh) rotate(720deg)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'slide-up': 'slideUp 0.5s ease-out forwards',
        'ticket-fly': 'ticketFly 2.5s ease-out forwards',
        'fade-up': 'fadeUp 200ms ease forwards',
      },
    },
  },
  plugins: [],
}
